version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: $DEV_USERNAME
      POSTGRES_PASSWORD: $DEV_PASSWORD
      POSTGRES_DB: $DEV_DATABASE
    volumes:
      - pg-dev-data:/var/lib/postgresql/data
    # env_file:
    #   - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DEV_USERNAME -d $DEV_DATABASE -h localhost -p 5432"]
      interval: 10s
      retries: 5

  app:
    build: 
      context: ./todo-app
      target: dev
    image: todo-app:dev
    ports:
      - "3000:3000"
    volumes:
      - ./todo-app:/app
    # env_file:
    #   - .env
    depends_on:
      db:
        condition: service_healthy  


volumes:
  pg-dev-data:
