version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: $PROD_USERNAME
      POSTGRES_PASSWORD: $PROD_PASSWORD
      POSTGRES_DB: $PROD_DATABASE
    volumes:
      - pg-prod-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $PROD_USERNAME -d $PROD_DATABASE -h localhost -p 5432"]
      interval: 10s
      retries: 5

  app:
    build: 
      context: ./todo-app
      target: production
    image: todo-app:prod
    ports:
      - "3010:3000"
    volumes:
      - ./todo-app:/app
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy  


volumes:
  pg-prod-data:
