apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: irshad1201/todo-app:dev
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "development"
            - name: POSTGRES_USER
              value: "postgres"  
            - name: POSTGRES_PASSWORD
              value: "DBPass"    
            - name: POSTGRES_DB
              value: "wd-todo-dev"  
            - name: DB_HOST
              value: postgres-service

---

apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: todo-app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: irshad1201/postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: NODE_ENV
              value: "development"
            - name: POSTGRES_USER
              value: "postgres"  
            - name: POSTGRES_PASSWORD
              value: "DBPass"    
            - name: POSTGRES_DB
              value: "wd-todo-dev"  
            - name: DB_HOST
              value: postgres-service
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---

