name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # services:
    #   postgres:
    #     image: postgres:15
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: DBPass
    #       POSTGRES_DB: wd-todo-dev
    #     ports:
    #       - 5432:5432
    #     options: >-
    #       --health-cmd="pg_isready"
    #       --health-interval=10s
    #       --health-timeout=5s
    #       --health-retries=3

    steps:

      # - name: Run tests
      #   run: cd todo-app && npm test

      - name: Build Docker image
        # run: docker build -t my-app:latest -f todo-app/Dockerfile ./todo-app
        run: docker-compose -f ../docker-compose-dev.yml build

