name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # services:
    #   postgres:
    #     image: postgres:15
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: DBPass
    #       POSTGRES_DB: wd-todo-dev
    #     ports:
    #       - 5432:5432
    #     options: >-
    #       --health-cmd="pg_isready"
    #       --health-interval=10s
    #       --health-timeout=5s
    #       --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      # - name: Run tests
      #   run: cd todo-app && npm test

      # - name: Navigate to todo-app directory
      #   run: cd wd201/todo-app

      - name: Build Docker Compose
        run: docker-compose -f docker-compose-prod.yml build

